server:
  port: 8081

spring:
  application:
    name: raffaele

  datasource:
    url: jdbc:mariadb://localhost:3306/video_store_exam?createDatabaseIfNotExist=true&autoReconnect=true&useSLL=false
    username:
    password:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false

logging:
  level:
    it.cgmconsulting.raffaele: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework: info

# Enable/Disable spring-doc
spring-doc:
  swagger-ui:
    enabled: true
